### ISSUE TITLE
Example in README.md does not work

### ISSUE THREAD

**Issue by mozai** [baniuyao/ZabbixPythonApi#10]
This is a follow-up to #5 which I can't reopen.
The example in README.md still does not work.

```
zapi.host.get({'hostids':[hostid],'output':'extend'})
Traceback (most recent call last):
  File "zapi_example.py", line 18, in <module>
    zapi.host.get({'hostids':[hostid],'output':'extend'})
  File "/root/zabbix_api/zapi.py", line 43, in __getattr__
    raise ZabbixAPIException('No such API object: %s' % name)
zapi.ZabbixAPIException: No such API object: host

print zapi.getHostByHostid(hostid)
Traceback (most recent call last):
  File "zapi_example.py", line 20, in <module>
    print zapi.getHostByHostid(hostid)
  File "/root/zabbix_api/zapi.py", line 43, in __getattr__
    raise ZabbixAPIException('No such API object: %s' % name)
zapi.ZabbixAPIException: No such API object: getHostByHostid
```

Using Python 2.7.6 and Zabbix 2.4.5

**Comment by yrjsg** [comment]
It is `zapi.Host.get`, not `zapi.host.get`. Please pay attention the case.

**Comment by mozai** [comment]
I did pay attention to the case!  Your readme.md file says

```
zapi.host.get({'hostids':['16913','17411'],'output':'extend'})
```

small h, not big H.  And you did not answer why 

```
print zapi.getHostByHostid('16913')
```

fails with "No such API object"

**Comment by yrjsg** [comment]
I think this is a problem in readme.md. `getHostByHostid` is a function existed in the former vision. I think in code I need to expose some basic module of Zabbix, not some wrapper functions like `getHostByHostid`. So I deleted it in current vision. I will modify readme.me.
