### ISSUE TITLE
alert.get fails with internal server error 500

### ISSUE THREAD

**Issue by rburkhal** [baniuyao/ZabbixPythonApi#13]
Using zapi.alert.get({'output': 'extend', 'limit': 1}),  I get the following:

HttpError: 500 Server Error: Internal server Error...

What could I be doing wrong or is there a bug?

**Comment by yrjsg** [comment]
can you provide the version of Zabbix?

**Comment by rburkhal** [comment]
So Sorry.  v0.5 - 24, May, 2012 is what I'm using, which works great by the way.  I just recently needed to get alert info and couldn't figure out how to get it working.

Thanks

**Comment by yrjsg** [comment]
okay, I'll close this issue if everything's fine.
