### ISSUE TITLE
ZabbixAPI Err: The "user.login" method must be called without the "auth" parameter

### ISSUE THREAD

**Issue by bark-beetle** [baniuyao/ZabbixPythonApi#8]
Zabbix 2.4

ZabbixAPI Err: The "user.login" method must be called without the "auth" parameter

    def json_obj(self, method, params):
        obj = { 'jsonrpc' : '2.0',
                'method'  : method,
                'params'  : params,
                'id'      : self.__id}
        ##### Zabbix 2.4 #####
        if self.isLogin():
            obj['auth'] = self.__auth
        ######################
        return json.dumps(obj)

**Comment by yrjsg** [comment]
Fixed by remove the `auth` in post request. Tests passed.
