### ISSUE TITLE
Can you write a python3 version?

### ISSUE THREAD

**Issue by 0312birdzhang** [baniuyao/ZabbixPythonApi#9]
I use 2to3 to convert,but it not works.
So,please write a python3 version :)

**Comment by yrjsg** [comment]
I'm not familiar with Python3. Could you please have a try with Python 2to3 tool at https://docs.python.org/2/library/2to3.html?

**Comment by 0312birdzhang** [comment]
@baniuyao I'm not familiar too :( 

I had tried 2to3,not perfect. Some bugs occured .

It's not very important,i just want to port it to my phone,and write a qml GUI,just for fun :)

**Comment by yrjsg** [comment]
I'm sorry that I have not made response here. This API under Python 3 is not on my plan currently. When Python 3 is popular enough, then let's do it:)

**Comment by 0312birdzhang** [comment]
@baniuyao 我还是用中文吧

刚提交了一个pr，简单改了改，在2.4下应该没问题。zabbix 2.5改了一些api，用不了。

**Comment by yrjsg** [comment]
好的，中英文都okay的。我晚上merge到一个单独的分支上

**Comment by yrjsg** [comment]
done on `ForPython3` branch.
